language: java

addons:
  sonarcloud:
    organization: retest
    token:
      secure: "${SONAR_CLOUD_TOKEN}"

notifications:
  email: false

cache:
  directories:
    - "${HOME}/.sonar/cache/"
    - "${HOME}/.m2/"

services:
  - docker

install: true

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -P deb,docker

deploy:
  - provider: releases
    api_key: "${GH_TOKEN}"
    file_glob: true
    file:
      - "./target/rebazer-*.jar"
      - "./target/rebazer-*.deb"
    skip_cleanup: true
    on:
      tags: true

  - provider: script
    script:
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" ;
        mvn dockerfile:push -Pdocker
    skip_cleanup: true
    on:
      tags: true
